services:
  postgres:
    image: postgres:16-alpine
    container_name: resilient-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resilient_microservices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./product-service/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d resilient_microservices"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: resilient-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    environment:
      PORT: 4001
      SERVICE_NAME: product-service
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: resilient_microservices
      REDIS_URL: redis://redis:6379
      CACHE_TTL_SECONDS: 60
    ports:
      - "4001:4001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    environment:
      PORT: 4002
      SERVICE_NAME: payment-service
    ports:
      - "4002:4002"

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      PORT: 4004
      SERVICE_NAME: auth-service
      JWT_SECRET: super-secret-jwt-key-change-later
      JWT_EXPIRES_IN: 1h
    ports:
      - "4004:4004"

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    environment:
      PORT: 4003
      SERVICE_NAME: order-service
      PAYMENT_SERVICE_URL: http://payment-service:4002
      PAYMENT_TIMEOUT_MS: 2000
      PAYMENT_MAX_RETRIES: 3
      CIRCUIT_BREAKER_FAILURE_THRESHOLD: 3
      CIRCUIT_BREAKER_COOLDOWN_MS: 60000
    ports:
      - "4003:4003"
    depends_on:
      - payment-service

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    environment:
      PORT: 4000
      SERVICE_NAME: api-gateway
      PRODUCT_SERVICE_URL: http://product-service:4001
      ORDER_SERVICE_URL: http://order-service:4003
      AUTH_SERVICE_URL: http://auth-service:4004
    ports:
      - "4000:4000"
    depends_on:
      - product-service
      - order-service
      - auth-service

volumes:
  postgres_data:
  redis_data: